### PR TITLE
Add option to customize apiserver's secure port. Default to port 6443 (based on k8s docs). Add --storage-backend option to kube-apiserver.yml.

### PR DESCRIPTION
**Pull request by puneetkatyal**

### CODE REVIEW

**Review by naveens — COMMENTED** [review]
Please comment why we are not using the default etcd3 storage backend. Are we planning to do upgrade later?

**Comment by puneetkatyal** [comment]
`etcd2` here was meant to be the default for the role. I've updated this to `etcd3` in coreos-ansible. I think it makes sense to have `etcd3` as default based on https://kubernetes.io/docs/admin/kube-apiserver/

I'll update the change.

**Comment by imkin** [comment]
Both the changes are unconnected should have been two PR's.

**Comment by puneetkatyal** [comment]
Split them into two separate pull requests. Discarding this.

https://github.com/vmware/ansible-coreos-kubernetes-master/pull/10
https://github.com/vmware/ansible-coreos-kubernetes-master/pull/11

**Pull request closed without merging**
